export const GET_ALL_PROFILES = 'GET_ALL_PROFILES';
export const ADD_PROFILE = 'ADD_PROFILE';
export const CONFIRM_LOGIN = 'CONFIRM_LOGIN';
export const CHANGE_ALUMNI_ID = 'CHANGE_ALUMNI_ID';
export const GET_SPECIFIC_ALUMNI = 'GET_SPECIFIC_ALUMNI';
export const GET_GRAD_DATES = 'GET_GRAD_DATES';
export const GET_PROFILE_DATA = 'GET_PROFILE_DATA';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';